#ifndef PRISM_MATERIAL_DEFINES
#define PRISM_MATERIAL_DEFINES

// convert technique to material
#if defined(TECHNIQUE_MESH) || defined(TECHNIQUE_DECAL) || defined(TECHNIQUE_DECAL_NOPREMULT) || defined(TECHNIQUE_DECAL_CUTOUT)
#define MATERIAL_STANDARD
#elif defined(TECHNIQUE_SHIELD_LIT)
#define MATERIAL_SHIELDLIT
#elif defined(TECHNIQUE_SHIELD)
#define MATERIAL_SHIELD
#elif defined(TECHNIQUE_GLASS)
#define MATERIAL_GLASS
#elif defined(TECHNIQUE_HOLO)
#define MATERIAL_HOLO
#elif defined(TECHNIQUE_ALPHA_MASKED) || defined(TECHNIQUE_ALPHA_MASKED_SINGLE_SIDED)
#define MATERIAL_ALPHAMASKED
#endif

#endif